### ISSUE TITLE
why the heck you uploaded mod with "i cant read this brainrot" in mindustry AAAAAAAHHHHHHHH

### ISSUE THREAD

**Issue by ZaharitIngot** [ItzCraft/Xanthia#1]

**Comment by ItzCraft** [comment]
Because the mod browser has a limit on the places in it. And if we dont upload it now, there chance that in future we wont be able to upload if. So we uploaded it into the mod browser, but we hoping that no one figured it out. But if you try to play, it's better to wait for the beta test!

**Comment by ZaharitIngot** [comment]
Oh, okay then

вт, 10 сент. 2024 г., 05:46 ItzCraft ***@***.***>:
